In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
import warnings

warnings.filterwarnings('ignore')

In [58]:
df = pd.read_csv('/content/pulsar_stars.csv')
df.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [59]:
df.isnull().sum()

 Mean of the integrated profile                  0
 Standard deviation of the integrated profile    0
 Excess kurtosis of the integrated profile       0
 Skewness of the integrated profile              0
 Mean of the DM-SNR curve                        0
 Standard deviation of the DM-SNR curve          0
 Excess kurtosis of the DM-SNR curve             0
 Skewness of the DM-SNR curve                    0
target_class                                     0
dtype: int64

In [60]:
df['target_class'].value_counts()

target_class
0    16259
1     1639
Name: count, dtype: int64

In [61]:
X = df.drop('target_class',axis=1)
y = df['target_class']

In [62]:
y

0        0
1        0
2        0
3        0
4        0
        ..
17893    0
17894    0
17895    0
17896    0
17897    0
Name: target_class, Length: 17898, dtype: int64

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=22)

In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred1 = lr.predict(X_test)
print(classification_report(y_test,y_pred1))
confusion_matrix(y_test,y_pred1)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      3235
           1       0.94      0.81      0.87       345

    accuracy                           0.98      3580
   macro avg       0.96      0.90      0.93      3580
weighted avg       0.98      0.98      0.98      3580

array([[3216,   19],
       [  65,  280]])

# Random Under Sampling

In [65]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=22)

In [66]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=44)
X_resampled,y_resampled = rus.fit_resample(X_train,y_train)

In [67]:
X_train.shape

(14318, 8)

In [68]:
X_resampled.shape

(2588, 8)

In [69]:
lr = LogisticRegression()
lr.fit(X_resampled,y_resampled)
y_pred2 = lr.predict(X_test)
print(classification_report(y_test,y_pred2))
confusion_matrix(y_test,y_pred2)

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      3235
           1       0.75      0.91      0.82       345

    accuracy                           0.96      3580
   macro avg       0.87      0.94      0.90      3580
weighted avg       0.97      0.96      0.96      3580

array([[3130,  105],
       [  31,  314]])

# Random Over Sampling

In [70]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=22)

In [71]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_resampled,y_resampled = ros.fit_resample(X_train,y_train)

In [72]:
X_train.shape

(14318, 8)

In [73]:
X_resampled.shape

(26048, 8)

In [74]:
lr = LogisticRegression()
lr.fit(X_resampled,y_resampled)
y_pred3 = lr.predict(X_test)
print(classification_report(y_test,y_pred3))
confusion_matrix(y_test,y_pred3)

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      3235
           1       0.75      0.91      0.82       345

    accuracy                           0.96      3580
   macro avg       0.87      0.94      0.90      3580
weighted avg       0.97      0.96      0.96      3580

array([[3130,  105],
       [  31,  314]])

# SMOTE

In [75]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=22)

In [76]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_resampled,y_resampled = smote.fit_resample(X_train,y_train)

In [77]:
X_train.shape

(14318, 8)

In [78]:
X_resampled.shape

(26048, 8)

In [79]:
lr = LogisticRegression()
lr.fit(X_resampled,y_resampled)
y_pred4 = lr.predict(X_test)
print(classification_report(y_test,y_pred4))
confusion_matrix(y_test,y_pred4)

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      3235
           1       0.75      0.91      0.82       345

    accuracy                           0.96      3580
   macro avg       0.87      0.94      0.90      3580
weighted avg       0.97      0.96      0.96      3580

array([[3129,  106],
       [  31,  314]])

# Balanced Random Forest

In [81]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=22)

In [83]:
from imblearn.ensemble import BalancedRandomForestClassifier
classifier = BalancedRandomForestClassifier()
classifier.fit(X_train,y_train)
y_pred5 = classifier.predict(X_test)
print(classification_report(y_test,y_pred5))
confusion_matrix(y_test,y_pred5)

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      3235
           1       0.80      0.90      0.85       345

    accuracy                           0.97      3580
   macro avg       0.89      0.94      0.91      3580
weighted avg       0.97      0.97      0.97      3580

array([[3155,   80],
       [  33,  312]])